# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.cache/wt [current_project]
set_property parent.project_path H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/new/Acce.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/PWM.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/car.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/finish.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/game_over.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/game_state.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/graphics.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/keyboard.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/list_ch14_01_font_rom.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/ps2_rx.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/road.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/project_3/seginterface.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/project_3/sevenseg.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/song1.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/start.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/text.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/time_text.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/vga_sync.v
  H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/sources_1/imports/FPGA-Racing-Game-master/top_race_game.v
}
read_ip -quiet H:/Documents/GitHub/12.4/Verilog_game/testgame2/testgame2.srcs/sources_1/ip/AccelerometerCtl2_2/AccelerometerCtl2_2.xci
set_property used_in_implementation false [get_files -all h:/Documents/GitHub/12.4/Verilog_game/testgame2/testgame2.srcs/sources_1/ip/AccelerometerCtl2_2/project_1.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/constrs_1/imports/FPGA-Racing-Game-master/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files H:/Documents/GitHub/12.4/Verilog_game/Racing/Racing.srcs/constrs_1/imports/FPGA-Racing-Game-master/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_race_game -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_race_game.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_race_game_utilization_synth.rpt -pb top_race_game_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
